name: cpk
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
    name: Cpk ${{ matrix.architecture }} on ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ SECRETS.GH_TOKEN }}
      DISPLAY: :0
    steps:
      - name: Setup Ninja and CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build
      - uses: actions/checkout@v2
      - name: Build CPK
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build -j16
